### ISSUE TITLE
Chapter 1. Basics of Rust Concurrency has a typo

### ISSUE THREAD

**Issue by Hofer-Julian** [m-ou-se/rust-atomics-and-locks#11] opened 2023-01-30 18:56 UTC
### Type of error

Typo

### Location of the error

https://marabos.nl/atomics/basics.html#parking

### Description of the error

```diff
- Scoped threads are useful to limit the lifetime of a thread to alllow
+ Scoped threads are useful to limit the lifetime of a thread to allow
```

**Comment by Imberflur** [comment] 2023-02-08 04:39
This may be a duplicate of https://github.com/m-ou-se/rust-atomics-and-locks/issues/9

@m-ou-se are fixes supposed to immediately propagate to the site?

**Comment by m-ou-se** [comment] 2023-02-08 14:38
Fixed!

> are fixes supposed to immediately propagate to the site?

Yes, but it looks like I did something wrong and uploaded some outdated files. Fixed. :)

**Closed as completed by m-ou-se** 2023-02-08 14:38 UTC
Labels: errata, confirmed
